# Diffs from e2e_glt_resource_config.yaml
# - Swap vertex_ai_inferencer_config for vertex_ai_graph_store_inferencer_config
# - Swap vertex_ai_trainer_config for vertex_ai_graph_store_trainer_config
shared_resource_config:
  resource_labels:
    cost_resource_group_tag: dev_experiments_COMPONENT
    cost_resource_group: gigl_platform
  common_compute_config:
    project: "external-snap-ci-github-gigl"
    region: "us-central1"
    temp_assets_bucket: "gs://gigl-cicd-temp"
    temp_regional_assets_bucket: "gs://gigl-cicd-temp"
    perm_assets_bucket: "gs://gigl-cicd-perm"
    temp_assets_bq_dataset_name: "gigl_temp_assets"
    embedding_bq_dataset_name: "gigl_embeddings"
    gcp_service_account_email: "untrusted-external-github-gigl@external-snap-ci-github-gigl.iam.gserviceaccount.com"
    dataflow_runner: "DataflowRunner"
preprocessor_config:
  edge_preprocessor_config:
    num_workers: 1
    max_num_workers: 128
    machine_type: "n2d-highmem-32"
    disk_size_gb: 300
  node_preprocessor_config:
    num_workers: 1
    max_num_workers: 128
    machine_type: "n2d-highmem-64"
    disk_size_gb: 300
trainer_resource_config:
  vertex_ai_graph_store_trainer_config:
    graph_store_pool:
      machine_type: n2-highmem-32
      gpu_type: ACCELERATOR_TYPE_UNSPECIFIED
      gpu_limit: 0
      num_replicas: 2
    compute_pool:
      machine_type: n1-standard-16
      gpu_type: NVIDIA_TESLA_T4
      gpu_limit: 2
      num_replicas: 2
inferencer_resource_config:
  vertex_ai_graph_store_inferencer_config:
    graph_store_pool:
      machine_type: n2-highmem-32
      gpu_type: ACCELERATOR_TYPE_UNSPECIFIED
      gpu_limit: 0
      num_replicas: 2
    compute_pool:
      machine_type: n1-standard-16
      gpu_type: NVIDIA_TESLA_T4
      gpu_limit: 2
      num_replicas: 2
